Testing
YunoHost-Apps/codimd_ynh pull request #45
Opened 2020-10-05 15:34 UTC by ericgaspar

## Problem
- *Root domain install only*

## Solution
- *Add the possibility to install in subfolder*

2020-10-05 15:37 UTC, ericgaspar commented
Didn't realize this wasn't merged to master...

2020-10-05 20:36 UTC, yalh76 requested changes

2020-10-05 20:36 UTC, yalh76 commented on conf/nginx.conf
> -  # Force usage of https
We should keep the force usage of https

2020-10-05 21:19 UTC, yalh76 approved these changes

2020-10-06 05:38 UTC, lapineige approved these changes

2020-10-08 18:03 UTC, yalh76 commented
Own CI results:

### Buster result: 97672fd18d0422ab052c95222e5fdf59d97f8f6c
![image](https://user-images.githubusercontent.com/30271971/95496411-16182d80-09a1-11eb-844e-970658fdb70b.png)

###Stretch result: 97672fd18d0422ab052c95222e5fdf59d97f8f6c
![image](https://user-images.githubusercontent.com/30271971/95496463-2cbe8480-09a1-11eb-8573-d4f91869e072.png)

2020-10-08 19:52 UTC, ericgaspar commented
On merge alors!?

2020-10-08 20:56 UTC, merged